version: '3.4' # run-migrations.sh

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: RetroCollect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: batatapalha
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./RetroCollectApi/Data/postgres-init.sql:/docker-entrypoint-initdb.d/meu-script-inserts.sql

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./RetroCollectApi/Data/mongodb-init.js:/docker-entrypoint-initdb.d/create-collection.js
      
  retrocollectapi:
    image: ${DOCKER_REGISTRY-}retrocollectapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_URLS=http://+:5000
#      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:5000"
#      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ./RetroCollectApi:/home/app
    depends_on:
      - postgres
      - mongo

volumes:
  postgres-data:
  mongo-data:
