version: '3.4'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "27000:5432"
    environment:
      POSTGRES_DB: RetroCollect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: batatapalha
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongodb-init.js:/docker-entrypoint-initdb.d/create-collection.js
      
  retrocollectapi:
    image: ${DOCKER_REGISTRY-}retrocollectapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "8080:5000" # HTTP
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ./RetroCollect:/home/app
    depends_on:
      - postgres
      - mongo

volumes:
  postgres-data:
  mongo-data:
